elems:

  - src: 'git/gitconfig'
    dst: '~/.gitconfig'

  - src:  'cabal/config'
    dst:  '~/.cabal/config'
    only: ['haskell']

  - src: 'cmus/(.+)'
    dst: '~/.cmus/<1>'
    only: ['cli_centric']

  - src: 'parcellite/(.+)'
    dst: '~/.config/parcellite/<1>'
    only: ['minimal_de']

  - src:  'feh/fehbg'
    dst:  '~/.fehbg'
    only: ['minimal_de']

  - src:  'gtk/bookmarks'
    dst:  '~/.gtk-bookmarks'
    only: ['gtk']

  - src: 'zim/(.+)'
    dst: '~/.config/zim/<1>'
    only: ['zim']
    notes:
      the enabled plugins have the following dependencies:
        diagram_editor     -> graphviz
        equation_editor    -> latex, dvipng
        gnu_r_ploteditor   -> gnu r
        gnuplot_ploteditor -> gnuplot
        screenshot         -> scrot
        linkmap            -> graphviz
        sourceview         -> gtksourceview2
        versioncontrol     -> (optional) bzr, hg, git
